create materialized view persoon.sterfte_aangehaakt_sas as
select
	'2017'::int as jaar,
	anummr,
	bsnumm,
	unicod,
	ovldat,
	ovllnd::int,
	ovlpls,
	gslcha,
	gbdtb8,
	leeftd,
	leeft1,
	lpad(lndgbb::char(4), 4, '0')::char(4) as lndgbb,
	gebpla,
	bevcbs,
	etncbs,
	lpad(natiob::char(3), 3, '0')::char(3) as natiob,
	vstdgr,
	vstdta,
	vstned,
	brgstb,
	codvbt,
	dathon,
	dathuw,
	dtbvbt,
	dtevbt,
	uniou1,
	uniou2,
	gslou1,
	gslou2,
	lpad(gblou1::char(4), 4, '0')::char(4) as gblou1,
	lpad(gblou2::char(4), 4, '0')::char(4) as gblou2,
	gbdou1,
	gbdou2,
	huisnr,
	huislt,
	hstoev,
	pttkod,
	adrs15,
	strkod,
	lpad(bagids::char(16), 16, '0')::char(16) as bagids,
	lpad(numids::char(16), 16, '0')::char(16) as numids,
	coalesce(brtk15, 'Z99z') as brtk15,
	coalesce(bctk15, 'Z99') as bctk15,
	coalesce(stad15, 'Z') as stad15,
	coalesce(i22geb, 'ZX99') as i22geb,
	coalesce(i27geb, 'ZY99') as i27geb,
	coalesce(altbrt15, 'ZS99') as altbrt15,
	coalesce(rayon15, 'ZA99') as rayon15,
	coalesce(brtk10, 'Z99z') as brtk10,
	tydber
from
	persoon.sterfte_aangehaakt
union all
select
	'2017'::int as jaar,
	anummr,
	bsnumm,
	unicod,
	ovldat,
	ovllnd::int,
	ovlpls,
	gslcha,
	gbdtb8,
	leeftd,
	leeft1,
	lpad(lndgbb::char(4), 4, '0')::char(4) as lndgbb,
	gebpla,
	bevcbs,
	etncbs,
	lpad(natiob::char(3), 3, '0')::char(4) as natiob,
	vstdgr,
	vstdta,
	vstned,
	brgstb,
	codvbt,
	dathon,
	dathuw,
	dtbvbt,
	dtevbt,
	uniou1,
	uniou2,
	gslou1,
	gslou2,
	lpad(gblou1::char(4), 4, '0')::char(4) as gblou1,
	lpad(gblou2::char(4), 4, '0')::char(4) as gblou2,
	gbdou1,
	gbdou2,
	huisnr,
	huislt,
	hstoev,
	pttkod,
	adrs15,
	strkod,
	lpad(bagids::char(16), 16, '0')::char(16) as bagids,
	lpad(numids::char(16), 16, '0')::char(16) as numids,
	coalesce(brtk15, 'Z99z') as brtk15,
	coalesce(bctk15, 'Z99') as bctk15,
	coalesce(stad15, 'Z') as stad15,
	coalesce(i22geb, 'ZX99') as i22geb,
	coalesce(i27geb, 'ZY99') as i27geb,
	coalesce(altbrt15, 'ZS99') as altbrt15,
	coalesce(rayon15, 'ZA99') as rayon15,
	coalesce(brtk10, 'Z99z') as brtk10,
	tydber
from
	persoon.sterfte_aangehaakt1